### ISSUE TITLE
Support for PHP 8?

### ISSUE THREAD

**Issue by djoos** [MarioBlazek/twig-byte-units-extension#2]
Hi there,

are there plans to add in support for PHP 8 for this Twig extension?

Thanks in advance!

Kind regards,
David

**Comment by MarioBlazek** [comment]
Hi @djoos, first thank you for the PR. Let me test this on PHP 8 and PHP 8.1. Will try to tag the release asap.

**Comment by djoos** [comment]
Perfect, thank you!
